#!/usr/bin/env python3
"""Reference-condition confidence quality, with uncertainty.

These are the secondary descriptive metrics at theta_0 - accuracy, mean
confidence, the gap between them and AUROC. They were previously quoted as bare
point estimates, which is the one thing the statistical requirements forbid:
an AUROC of 0.437 either excludes chance or it does not, and a point estimate
cannot say which. Each metric therefore carries an item-clustered bootstrap
interval computed here.

Descriptive and exploratory. Nothing here selects a threshold, enters the
confirmatory family or is corrected for multiplicity; the calibration threshold
artifact is untouched and is not regenerated by this script.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
from datetime import datetime, timezone
from pathlib import Path
from statistics import fmean

from cpis.analysis.matrix import _auroc, _resolve_official_scores
from cpis.analysis.metrics import has_valid_confidence
from cpis.matrix_config import load_matrix_config
from cpis.matrix_records import MatrixParsedRecord
from cpis.storage import StorageLayout, read_json


def _pav(x: list[float], y: list[float]) -> list[float]:
    """Pool-adjacent-violators isotonic regression of y on x.

    Returns the non-decreasing fit evaluated at each input, which is the CORP
    recalibration: the best-fitting monotone relabelling of the forecasts. It
    needs no bins, which is the point - reliability diagrams built on arbitrary
    bin edges move when the edges move.
    """
    # Observations sharing a forecast value must share a fitted value. Ordering
    # ties by the outcome would let the outcome decide the ordering, which
    # manufactures discrimination out of a forecast that has none - and these
    # forecasts are heavily tied, so that is not a hypothetical.
    groups: dict[float, list[float]] = {}
    for value, outcome in zip(x, y):
        groups.setdefault(value, []).append(outcome)
    levels = sorted(groups)
    blocks: list[list[float]] = []
    for level in levels:
        outcomes = groups[level]
        blocks.append([fmean(outcomes), float(len(outcomes))])
        while len(blocks) > 1 and blocks[-2][0] > blocks[-1][0] + 1e-15:
            total = blocks[-2][0] * blocks[-2][1] + blocks[-1][0] * blocks[-1][1]
            weight = blocks[-2][1] + blocks[-1][1]
            blocks[-2:] = [[total / weight, weight]]
    fitted_by_level: dict[float, float] = {}
    position = 0
    for mean, weight in blocks:
        remaining = int(weight)
        while remaining > 0:
            level = levels[position]
            fitted_by_level[level] = mean
            remaining -= len(groups[level])
            position += 1
    return [fitted_by_level[value] for value in x]


def _corp(confidences: list[float], outcomes: list[int]) -> dict[str, float | None]:
    """CORP decomposition of the Brier score: BS = MCB - DSC + UNC.

    MCB is what is lost to miscalibration, DSC is what is gained over always
    predicting the base rate, and UNC is the irreducible outcome variance. It
    separates two failures the mean gap and AUROC each see only partly: a
    forecast can be badly scaled but well ordered, or perfectly scaled and
    uninformative.
    """
    if not confidences:
        return {k: None for k in ("brier", "mcb", "dsc", "unc", "base_rate")}
    n = len(confidences)
    base = fmean(outcomes)
    recalibrated = _pav(confidences, [float(o) for o in outcomes])
    brier = sum((c - o) ** 2 for c, o in zip(confidences, outcomes)) / n
    brier_recalibrated = sum(
        (r - o) ** 2 for r, o in zip(recalibrated, outcomes)
    ) / n
    brier_marginal = base * (1.0 - base)
    return {
        "brier": brier,
        "mcb": brier - brier_recalibrated,
        "dsc": brier_marginal - brier_recalibrated,
        "unc": brier_marginal,
        "base_rate": base,
    }


def _metrics(records: list[MatrixParsedRecord]) -> dict[str, float | None]:
    valid = [r for r in records if has_valid_confidence(r)]
    accuracy = fmean(int(bool(r.correct)) for r in records) if records else None
    mean_confidence = fmean(float(r.confidence) for r in valid) if valid else None
    corp = _corp(
        [float(r.confidence) for r in valid], [int(bool(r.correct)) for r in valid]
    )
    return {
        "accuracy": accuracy,
        "mean_confidence": mean_confidence,
        "confidence_accuracy_gap": (
            None
            if mean_confidence is None or accuracy is None
            else mean_confidence - accuracy
        ),
        "auroc": _auroc(records),
        "brier": corp["brier"],
        "brier_miscalibration": corp["mcb"],
        "brier_discrimination": corp["dsc"],
        "brier_uncertainty": corp["unc"],
        # Normalised against the base-rate forecast so pairs with very
        # different accuracies can be compared. The skill score is negative
        # whenever the reported confidence scores worse than always predicting
        # the base rate; discrimination skill is the share of that base-rate
        # uncertainty the forecast's ordering actually resolves.
        # BSS = (DSC - MCB)/UNC, so a negative skill score says exactly that
        # miscalibration outweighs whatever discrimination the forecast has.
        # Both ratios are reported because only their difference is visible in
        # the skill score, and they are separate failures.
        "brier_skill_score": (
            None
            if not corp["unc"]
            else 1.0 - corp["brier"] / corp["unc"]
        ),
        "discrimination_skill": (
            None if not corp["unc"] else corp["dsc"] / corp["unc"]
        ),
        "miscalibration_ratio": (
            None if not corp["unc"] else corp["mcb"] / corp["unc"]
        ),
    }


def _interval(
    records: list[MatrixParsedRecord], replicates: int, seed: int
) -> dict[str, dict]:
    """Percentile bootstrap resampling items with replacement.

    Each item contributes one reference observation, so the item cluster and the
    observation coincide here; resampling items keeps the unit of analysis the
    item regardless.
    """
    point = _metrics(records)
    rng = random.Random(seed)
    draws: dict[str, list[float]] = {k: [] for k in point}
    size = len(records)
    for _ in range(replicates):
        sample = [records[rng.randrange(size)] for _ in range(size)]
        for key, value in _metrics(sample).items():
            if value is not None:
                draws[key].append(value)
    out: dict[str, dict] = {}
    for key, value in point.items():
        ordered = sorted(draws[key])
        low = high = None
        if len(ordered) >= 20:
            low = ordered[int(0.025 * (len(ordered) - 1))]
            high = ordered[int(0.975 * (len(ordered) - 1))]
        out[key] = {
            "estimate": None if value is None else round(value, 6),
            "ci_low": None if low is None else round(low, 6),
            "ci_high": None if high is None else round(high, 6),
            "replicates": len(ordered),
        }
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", type=Path, default=Path.cwd())
    parser.add_argument("--configs", type=Path, default=Path("configs/core/calibration"))
    parser.add_argument(
        "--condition",
        default=None,
        help=(
            "restrict to one answer condition. Required for a run that carries "
            "several: probability quality is a property of a single coordinate, "
            "and mixing coordinates would average two different forecasters."
        ),
    )
    parser.add_argument("--partition-label", default=None)
    parser.add_argument("--destination", type=Path, required=True)
    parser.add_argument("--replicates", type=int, default=5000)
    parser.add_argument("--seed", type=int, default=20260922)
    args = parser.parse_args()

    root = args.repository_root.resolve()
    entries = []
    for path in sorted((root / args.configs).glob("*.yaml")):
        config = load_matrix_config(path)
        storage = StorageLayout.from_spec(config.storage, root)
        run = storage.output_root / config.run_id
        paths = sorted((run / "parsed").glob("*.json"))
        records = [MatrixParsedRecord.model_validate(read_json(p)) for p in paths]
        records = _resolve_official_scores(
            type("R", (), {"derived": run / "derived"})(), records, paths
        )
        unscored = [r for r in records if r.correct is None]
        if unscored:
            raise RuntimeError(f"{config.run_id}: {len(unscored)} unscored records")
        coupled = [r for r in records if "coupled" in r.design_roles]
        conditions = {r.answer_condition_id for r in coupled}
        if args.condition is not None:
            coupled = [r for r in coupled if r.answer_condition_id == args.condition]
            if not coupled:
                raise RuntimeError(
                    f"{config.run_id} has no records for condition {args.condition}"
                )
        elif len(conditions) > 1:
            raise RuntimeError(
                f"{config.run_id} carries {sorted(conditions)}; pass --condition "
                f"to say which coordinate these metrics describe"
            )
        metrics = _interval(coupled, args.replicates, args.seed)
        auroc = metrics["auroc"]
        entries.append(
            {
                "experiment_id": config.experiment_id,
                "run_id": config.run_id,
                "model_id": config.model.model_id,
                "model_mode": config.model.model_mode,
                "dataset_id": config.dataset.dataset_id,
                "items": len(coupled),
                "metrics": metrics,
                "auroc_excludes_chance": (
                    None
                    if auroc["ci_low"] is None
                    else bool(auroc["ci_low"] > 0.5 or auroc["ci_high"] < 0.5)
                ),
            }
        )

    payload = {
        "schema_version": "1.0",
        "artifact": "cpis-reference-confidence-quality-v1",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": "secondary descriptive; not confirmatory and not multiplicity corrected",
        "condition": args.condition or "reference",
        "partition": args.partition_label or "calibration",
        "bootstrap": {"unit": "dataset item", "replicates": args.replicates, "seed": args.seed},
        "pairs": entries,
    }
    body = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    payload["artifact_sha256"] = hashlib.sha256(body.encode("utf-8")).hexdigest()
    destination = (root / args.destination).resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    for e in entries:
        a = e["metrics"]["auroc"]
        g = e["metrics"]["confidence_accuracy_gap"]
        ci = "-" if a["ci_low"] is None else f"[{a['ci_low']:.3f}, {a['ci_high']:.3f}]"
        print(
            f"  {e['model_id'].split('/')[-1][:24]:<26}{e['model_mode']:<13}"
            f"{('ManyIFEval' if 'Instruct' in e['dataset_id'] else 'SuperGPQA'):<12}"
            f"AUROC={a['estimate']:.3f} {ci:<18}"
            f"excludes chance={str(e['auroc_excludes_chance']):<6}"
            f"gap={g['estimate']:+.3f} [{g['ci_low']:+.3f}, {g['ci_high']:+.3f}]"
        )


if __name__ == "__main__":
    main()
